# Generates lib/l10n/app_*.arb from one table. Run after every change.
import json, os

K = {}  # key -> {lang: text}
def s(key, **t): K[key] = t

s('appName', en='Pounce', de='Pounce', fr='Pounce', ru='Pounce', hu='Pounce', vi='Pounce', ar='Pounce')
s('navHome', en='Home', de='Start', fr='Accueil', ru='Главная', hu='Kezdőlap', vi='Trang chủ', ar='الرئيسية')
s('navSearch', en='Search', de='Suche', fr='Recherche', ru='Поиск', hu='Keresés', vi='Tìm kiếm', ar='بحث')
s('navLibrary', en='Library', de='Bibliothek', fr='Bibliothèque', ru='Медиатека', hu='Könyvtár', vi='Thư viện', ar='المكتبة')
s('navSettings', en='Settings', de='Einstellungen', fr='Paramètres', ru='Настройки', hu='Beállítások', vi='Cài đặt', ar='الإعدادات')
s('greetingMorning', en='Good morning', de='Guten Morgen', fr='Bonjour', ru='Доброе утро', hu='Jó reggelt', vi='Chào buổi sáng', ar='صباح الخير')
s('greetingAfternoon', en='Good afternoon', de='Guten Tag', fr='Bon après-midi', ru='Добрый день', hu='Szép napot', vi='Chào buổi chiều', ar='مساء الخير')
s('greetingEvening', en='Good evening', de='Guten Abend', fr='Bonsoir', ru='Добрый вечер', hu='Jó estét', vi='Chào buổi tối', ar='مساء الخير')
s('homeContinue', en='Jump back in', de='Weiterhören', fr='Reprendre', ru='Продолжить', hu='Folytatás', vi='Nghe tiếp', ar='تابع الاستماع')
s('homeBecauseYouPlayed', en='Because you played {title}', de='Weil du {title} gehört hast', fr='Parce que vous avez écouté {title}', ru='Потому что вы слушали {title}', hu='Mert ezt hallgattad: {title}', vi='Vì bạn đã nghe {title}', ar='لأنك استمعت إلى {title}')
s('errorLoading', en="Couldn't load content", de='Inhalte konnten nicht geladen werden', fr='Impossible de charger le contenu', ru='Не удалось загрузить', hu='Nem sikerült betölteni', vi='Không thể tải nội dung', ar='تعذّر تحميل المحتوى')
s('retry', en='Retry', de='Erneut versuchen', fr='Réessayer', ru='Повторить', hu='Újra', vi='Thử lại', ar='إعادة المحاولة')
s('noResults', en='No results', de='Keine Ergebnisse', fr='Aucun résultat', ru='Ничего не найдено', hu='Nincs találat', vi='Không có kết quả', ar='لا توجد نتائج')
s('searchHint', en='Songs, artists, playlists or links', de='Songs, Künstler, Playlists oder Links', fr='Titres, artistes, playlists ou liens', ru='Треки, исполнители, плейлисты или ссылки', hu='Dalok, előadók, lejátszási listák vagy linkek', vi='Bài hát, nghệ sĩ, danh sách phát hoặc liên kết', ar='أغانٍ أو فنانون أو قوائم تشغيل أو روابط')
s('searchRecent', en='Recent searches', de='Letzte Suchen', fr='Recherches récentes', ru='Недавние запросы', hu='Legutóbbi keresések', vi='Tìm kiếm gần đây', ar='عمليات البحث الأخيرة')
s('searchEmptyTitle', en='Find something to play', de='Finde etwas zum Abspielen', fr='Trouvez quelque chose à écouter', ru='Найдите, что послушать', hu='Keress valamit, amit meghallgatnál', vi='Tìm thứ gì đó để nghe', ar='ابحث عن شيء لتشغيله')
s('tabTracks', en='Tracks', de='Tracks', fr='Titres', ru='Треки', hu='Számok', vi='Bài hát', ar='المقاطع')
s('tabPlaylists', en='Playlists', de='Playlists', fr='Playlists', ru='Плейлисты', hu='Listák', vi='Danh sách phát', ar='قوائم التشغيل')
s('tabAlbums', en='Albums', de='Alben', fr='Albums', ru='Альбомы', hu='Albumok', vi='Album', ar='الألبومات')
s('tabArtists', en='Artists', de='Künstler', fr='Artistes', ru='Исполнители', hu='Előadók', vi='Nghệ sĩ', ar='الفنانون')
s('likedTracks', en='Liked tracks', de='Lieblingstracks', fr='Titres aimés', ru='Любимые треки', hu='Kedvelt számok', vi='Bài hát đã thích', ar='المقاطع المفضلة')
s('history', en='History', de='Verlauf', fr='Historique', ru='История', hu='Előzmények', vi='Lịch sử', ar='السجل')
s('playlists', en='Playlists', de='Playlists', fr='Playlists', ru='Плейлисты', hu='Lejátszási listák', vi='Danh sách phát', ar='قوائم التشغيل')
s('newPlaylist', en='New playlist', de='Neue Playlist', fr='Nouvelle playlist', ru='Новый плейлист', hu='Új lista', vi='Danh sách phát mới', ar='قائمة تشغيل جديدة')
s('playlistName', en='Name', de='Name', fr='Nom', ru='Название', hu='Név', vi='Tên', ar='الاسم')
s('create', en='Create', de='Erstellen', fr='Créer', ru='Создать', hu='Létrehozás', vi='Tạo', ar='إنشاء')
s('cancel', en='Cancel', de='Abbrechen', fr='Annuler', ru='Отмена', hu='Mégse', vi='Hủy', ar='إلغاء')
s('rename', en='Rename', de='Umbenennen', fr='Renommer', ru='Переименовать', hu='Átnevezés', vi='Đổi tên', ar='إعادة التسمية')
s('delete', en='Delete', de='Löschen', fr='Supprimer', ru='Удалить', hu='Törlés', vi='Xóa', ar='حذف')
s('deletePlaylistConfirm', en='Delete "{name}"?', de='„{name}“ löschen?', fr='Supprimer « {name} » ?', ru='Удалить «{name}»?', hu='Törlöd: „{name}”?', vi='Xóa "{name}"?', ar='حذف "{name}"؟')
s('clearHistory', en='Clear history', de='Verlauf löschen', fr="Effacer l'historique", ru='Очистить историю', hu='Előzmények törlése', vi='Xóa lịch sử', ar='مسح السجل')
s('emptyLikes', en='Tracks you like appear here', de='Tracks, die du likest, erscheinen hier', fr='Les titres que vous aimez apparaissent ici', ru='Здесь появятся понравившиеся треки', hu='A kedvelt számok itt jelennek meg', vi='Bài hát bạn thích sẽ xuất hiện ở đây', ar='تظهر هنا المقاطع التي تعجبك')
s('emptyHistory', en='Nothing played yet', de='Noch nichts gehört', fr="Rien d'écouté pour l'instant", ru='Вы ещё ничего не слушали', hu='Még nem hallgattál semmit', vi='Chưa phát gì', ar='لم يتم تشغيل أي شيء بعد')
s('emptyPlaylist', en='This playlist is empty', de='Diese Playlist ist leer', fr='Cette playlist est vide', ru='Плейлист пуст', hu='Ez a lista üres', vi='Danh sách phát này trống', ar='قائمة التشغيل هذه فارغة')
s('emptyPlaylists', en='Create playlists and add tracks via the ⋮ menu.', de='Erstelle Playlists und füge Tracks über das ⋮-Menü hinzu.', fr='Créez des playlists et ajoutez des titres via le menu ⋮.', ru='Создавайте плейлисты и добавляйте треки через меню ⋮.', hu='Hozz létre listákat, és adj hozzá számokat a ⋮ menüvel.', vi='Tạo danh sách phát và thêm bài hát qua menu ⋮.', ar='أنشئ قوائم تشغيل وأضف مقاطع عبر القائمة ⋮.')
s('tracksCount',
  en='{count, plural, =0{No tracks} =1{1 track} other{{count} tracks}}',
  de='{count, plural, =0{Keine Tracks} =1{1 Track} other{{count} Tracks}}',
  fr='{count, plural, =0{Aucun titre} one{{count} titre} other{{count} titres}}',
  ru='{count, plural, =0{Нет треков} one{{count} трек} few{{count} трека} many{{count} треков} other{{count} трека}}',
  hu='{count, plural, =0{Nincs szám} other{{count} szám}}',
  vi='{count, plural, =0{Không có bài hát} other{{count} bài hát}}',
  ar='{count, plural, zero{لا توجد مقاطع} one{مقطع واحد} two{مقطعان} few{{count} مقاطع} many{{count} مقطعًا} other{{count} مقطع}}')
s('followers', en='{count} followers', de='{count} Follower', fr='{count} abonnés', ru='Подписчики: {count}', hu='{count} követő', vi='{count} người theo dõi', ar='{count} متابع')
s('playNext', en='Play next', de='Als Nächstes abspielen', fr='Lire ensuite', ru='Играть следующим', hu='Lejátszás következőként', vi='Phát tiếp theo', ar='التشغيل التالي')
s('addToQueue', en='Add to queue', de='Zur Warteschlange', fr="Ajouter à la file d'attente", ru='Добавить в очередь', hu='Hozzáadás a sorhoz', vi='Thêm vào hàng đợi', ar='إضافة إلى قائمة الانتظار')
s('addToPlaylist', en='Add to playlist', de='Zu Playlist hinzufügen', fr='Ajouter à une playlist', ru='Добавить в плейлист', hu='Hozzáadás listához', vi='Thêm vào danh sách phát', ar='إضافة إلى قائمة تشغيل')
s('removeFromPlaylist', en='Remove from playlist', de='Aus Playlist entfernen', fr='Retirer de la playlist', ru='Удалить из плейлиста', hu='Eltávolítás a listából', vi='Xóa khỏi danh sách phát', ar='إزالة من قائمة التشغيل')
s('like', en='Like', de='Liken', fr="J'aime", ru='Нравится', hu='Kedvelés', vi='Thích', ar='إعجاب')
s('unlike', en='Remove from likes', de='Aus Likes entfernen', fr='Retirer des titres aimés', ru='Убрать из любимых', hu='Eltávolítás a kedveltek közül', vi='Bỏ thích', ar='إزالة من المفضلة')
s('goToArtist', en='Go to artist', de='Zum Künstler', fr="Voir l'artiste", ru='Перейти к исполнителю', hu='Ugrás az előadóhoz', vi='Đến trang nghệ sĩ', ar='الانتقال إلى الفنان')
s('copyLink', en='Copy link', de='Link kopieren', fr='Copier le lien', ru='Копировать ссылку', hu='Link másolása', vi='Sao chép liên kết', ar='نسخ الرابط')
s('linkCopied', en='Link copied', de='Link kopiert', fr='Lien copié', ru='Ссылка скопирована', hu='Link másolva', vi='Đã sao chép liên kết', ar='تم نسخ الرابط')
s('addedToQueue', en='Added to queue', de='Zur Warteschlange hinzugefügt', fr="Ajouté à la file d'attente", ru='Добавлено в очередь', hu='Hozzáadva a sorhoz', vi='Đã thêm vào hàng đợi', ar='تمت الإضافة إلى قائمة الانتظار')
s('addedToPlaylist', en='Added to {name}', de='Zu {name} hinzugefügt', fr='Ajouté à {name}', ru='Добавлено в «{name}»', hu='Hozzáadva: {name}', vi='Đã thêm vào {name}', ar='تمت الإضافة إلى {name}')
s('alreadyInPlaylist', en='Already in {name}', de='Schon in {name}', fr='Déjà dans {name}', ru='Уже в «{name}»', hu='Már szerepel itt: {name}', vi='Đã có trong {name}', ar='موجود بالفعل في {name}')
s('nowPlaying', en='Now playing', de='Läuft gerade', fr='En cours de lecture', ru='Сейчас играет', hu='Most szól', vi='Đang phát', ar='قيد التشغيل الآن')
s('queue', en='Queue', de='Warteschlange', fr="File d'attente", ru='Очередь', hu='Lejátszási sor', vi='Hàng đợi', ar='قائمة الانتظار')
s('lyrics', en='Lyrics', de='Songtext', fr='Paroles', ru='Текст', hu='Dalszöveg', vi='Lời bài hát', ar='الكلمات')
s('noLyrics', en='No lyrics found', de='Kein Songtext gefunden', fr='Aucunes paroles trouvées', ru='Текст не найден', hu='Nem található dalszöveg', vi='Không tìm thấy lời bài hát', ar='لم يتم العثور على كلمات')
s('lyricsSource', en='Lyrics: {source}', de='Songtext: {source}', fr='Paroles : {source}', ru='Текст: {source}', hu='Dalszöveg: {source}', vi='Lời bài hát: {source}', ar='الكلمات: {source}')
s('sleepTimer', en='Sleep timer', de='Schlaf-Timer', fr='Minuteur de veille', ru='Таймер сна', hu='Elalvási időzítő', vi='Hẹn giờ ngủ', ar='مؤقت النوم')
s('sleepOff', en='Turn off timer', de='Timer ausschalten', fr='Désactiver le minuteur', ru='Выключить таймер', hu='Időzítő kikapcsolása', vi='Tắt hẹn giờ', ar='إيقاف المؤقت')
s('sleepIn', en='Stops in {minutes} min', de='Stoppt in {minutes} Min.', fr='Arrêt dans {minutes} min', ru='Остановка через {minutes} мин', hu='Leáll {minutes} perc múlva', vi='Dừng sau {minutes} phút', ar='يتوقف بعد {minutes} د')
s('minutes', en='{count} min', de='{count} Min.', fr='{count} min', ru='{count} мин', hu='{count} perc', vi='{count} phút', ar='{count} دقيقة')
s('speed', en='Speed', de='Tempo', fr='Vitesse', ru='Скорость', hu='Sebesség', vi='Tốc độ', ar='السرعة')
s('shuffle', en='Shuffle', de='Zufall', fr='Aléatoire', ru='Перемешать', hu='Keverés', vi='Trộn bài', ar='ترتيب عشوائي')
s('repeatOff', en='Repeat off', de='Wiederholen aus', fr='Répétition désactivée', ru='Повтор выключен', hu='Ismétlés ki', vi='Tắt lặp lại', ar='التكرار متوقف')
s('repeatAll', en='Repeat all', de='Alle wiederholen', fr='Tout répéter', ru='Повторять все', hu='Összes ismétlése', vi='Lặp lại tất cả', ar='تكرار الكل')
s('repeatOne', en='Repeat one', de='Einen wiederholen', fr='Répéter un titre', ru='Повторять один', hu='Egy ismétlése', vi='Lặp lại một bài', ar='تكرار مقطع واحد')
s('play', en='Play', de='Abspielen', fr='Lire', ru='Играть', hu='Lejátszás', vi='Phát', ar='تشغيل')
s('pause', en='Pause', de='Pause', fr='Pause', ru='Пауза', hu='Szünet', vi='Tạm dừng', ar='إيقاف مؤقت')
s('next', en='Next', de='Weiter', fr='Suivant', ru='Следующий', hu='Következő', vi='Tiếp theo', ar='التالي')
s('previous', en='Previous', de='Zurück', fr='Précédent', ru='Предыдущий', hu='Előző', vi='Trước', ar='السابق')
s('popularTracks', en='Popular', de='Beliebt', fr='Populaires', ru='Популярное', hu='Népszerű', vi='Phổ biến', ar='الأكثر شعبية')
s('playbackError', en="Can't play this track", de='Dieser Track kann nicht abgespielt werden', fr='Impossible de lire ce titre', ru='Не удаётся воспроизвести трек', hu='Ez a szám nem játszható le', vi='Không thể phát bài hát này', ar='تعذّر تشغيل هذا المقطع')
s('preview', en='Preview', de='Vorschau', fr='Extrait', ru='Превью', hu='Előnézet', vi='Bản xem trước', ar='معاينة')
s('protected', en='Protected', de='Geschützt', fr='Protégé', ru='Защищено', hu='Védett', vi='Được bảo vệ', ar='محمي')
s('protectedHint', en='This track is DRM-protected and can’t be played in Pounce yet – even when signed in', de='Dieser Track ist DRM-geschützt und in Pounce noch nicht abspielbar – auch nicht mit Anmeldung', fr='Ce titre est protégé par DRM et ne peut pas encore être lu dans Pounce, même connecté', ru='Трек защищён DRM и пока не воспроизводится в Pounce – даже после входа', hu='Ez a szám DRM-védett, és a Pounce még nem tudja lejátszani – bejelentkezve sem', vi='Bài hát này được bảo vệ DRM và Pounce chưa thể phát – kể cả khi đã đăng nhập', ar='هذا المقطع محمي بإدارة الحقوق الرقمية ولا يمكن لـ Pounce تشغيله بعد، حتى بعد تسجيل الدخول')
s('protectedPlayable', en='DRM-protected – decrypted by your browser’s DRM module', de='DRM-geschützt – entschlüsselt vom DRM-Modul deines Browsers', fr='Protégé par DRM – déchiffré par le module DRM de votre navigateur', ru='Защищено DRM – расшифровывается DRM-модулем браузера', hu='DRM-védett – a böngésző DRM-modulja oldja fel', vi='Được bảo vệ DRM – do mô-đun DRM của trình duyệt giải mã', ar='محمي بإدارة الحقوق الرقمية – تفك وحدة DRM في متصفحك تشفيره')
s('account', en='Account', de='Konto', fr='Compte', ru='Аккаунт', hu='Fiók', vi='Tài khoản', ar='الحساب')
s('login', en='Sign in with SoundCloud', de='Mit SoundCloud anmelden', fr='Se connecter avec SoundCloud', ru='Войти через SoundCloud', hu='Bejelentkezés SoundClouddal', vi='Đăng nhập bằng SoundCloud', ar='تسجيل الدخول عبر SoundCloud')
s('loginSubtitle', en='Sync likes, playlists and your stream', de='Likes, Playlists und deinen Stream synchronisieren', fr='Synchroniser titres aimés, playlists et votre flux', ru='Синхронизация лайков, плейлистов и ленты', hu='Kedvelések, listák és a hírfolyam szinkronizálása', vi='Đồng bộ lượt thích, danh sách phát và luồng của bạn', ar='مزامنة الإعجابات وقوائم التشغيل وبثّك')
s('signup', en='Create account', de='Konto erstellen', fr='Créer un compte', ru='Создать аккаунт', hu='Fiók létrehozása', vi='Tạo tài khoản', ar='إنشاء حساب')
s('loginPrivacy', en='You sign in on SoundCloud’s own page. Pounce never sees your password.', de='Die Anmeldung läuft auf der Seite von SoundCloud. Pounce sieht dein Passwort nie.', fr='La connexion se fait sur la page de SoundCloud. Pounce ne voit jamais votre mot de passe.', ru='Вход происходит на странице SoundCloud. Pounce не видит ваш пароль.', hu='A bejelentkezés a SoundCloud oldalán történik. A Pounce sosem látja a jelszavadat.', vi='Bạn đăng nhập trên trang của SoundCloud. Pounce không bao giờ thấy mật khẩu của bạn.', ar='يتم تسجيل الدخول على صفحة SoundCloud نفسها، ولا يرى Pounce كلمة مرورك أبدًا.')
s('loginWaiting', en='Finish signing in in the browser…', de='Schließe die Anmeldung im Browser ab …', fr='Terminez la connexion dans le navigateur…', ru='Завершите вход в браузере…', hu='Fejezd be a bejelentkezést a böngészőben…', vi='Hoàn tất đăng nhập trong trình duyệt…', ar='أكمل تسجيل الدخول في المتصفح…')
s('loginReopen', en='Open again', de='Erneut öffnen', fr='Rouvrir', ru='Открыть снова', hu='Újra megnyitás', vi='Mở lại', ar='فتح مرة أخرى')
s('loginPasteLabel', en='Paste redirect link', de='Rückleitungs-Link einfügen', fr='Coller le lien de redirection', ru='Вставьте ссылку перенаправления', hu='Átirányító link beillesztése', vi='Dán liên kết chuyển hướng', ar='الصق رابط إعادة التوجيه')
s('loginPasteHint', en='After signing in, SoundCloud redirects to a link starting with sc://auth?code=… If the app doesn’t pick it up automatically, copy it here.', de='Nach der Anmeldung leitet SoundCloud auf einen Link sc://auth?code=… weiter. Falls die App ihn nicht automatisch erhält, füge ihn hier ein.', fr='Après la connexion, SoundCloud redirige vers un lien sc://auth?code=… Si l’app ne le reçoit pas automatiquement, collez-le ici.', ru='После входа SoundCloud перенаправляет на ссылку sc://auth?code=… Если приложение не получило её автоматически, вставьте её сюда.', hu='Bejelentkezés után a SoundCloud egy sc://auth?code=… linkre irányít. Ha az app nem kapja meg automatikusan, illeszd be ide.', vi='Sau khi đăng nhập, SoundCloud chuyển hướng tới liên kết sc://auth?code=… Nếu ứng dụng không tự nhận được, hãy dán vào đây.', ar='بعد تسجيل الدخول يعيد SoundCloud التوجيه إلى رابط يبدأ بـ sc://auth?code=… إذا لم يستلمه التطبيق تلقائيًا فالصقه هنا.')
s('loginPasteHintWeb', en='A new tab opens. After signing in it shows an address like soundcloud.com/signin/callback?code=… Copy that address and paste it here.', de='Es öffnet sich ein neuer Tab. Nach der Anmeldung steht dort eine Adresse wie soundcloud.com/signin/callback?code=… Kopiere diese Adresse und füge sie hier ein.', fr='Un nouvel onglet s’ouvre. Après la connexion, il affiche une adresse du type soundcloud.com/signin/callback?code=… Copiez cette adresse et collez-la ici.', ru='Откроется новая вкладка. После входа в ней будет адрес вида soundcloud.com/signin/callback?code=… Скопируйте этот адрес и вставьте сюда.', hu='Új lap nyílik meg. Bejelentkezés után egy soundcloud.com/signin/callback?code=… címet mutat. Másold ki és illeszd be ide.', vi='Một thẻ mới sẽ mở. Sau khi đăng nhập, thẻ hiển thị địa chỉ dạng soundcloud.com/signin/callback?code=… Hãy sao chép địa chỉ đó và dán vào đây.', ar='ستُفتح علامة تبويب جديدة. بعد تسجيل الدخول سيظهر عنوان مثل soundcloud.com/signin/callback?code=… انسخ هذا العنوان والصقه هنا.')
s('loginConfirm', en='Continue', de='Weiter', fr='Continuer', ru='Продолжить', hu='Tovább', vi='Tiếp tục', ar='متابعة')
s('loginFailed', en='Sign-in failed', de='Anmeldung fehlgeschlagen', fr='Échec de la connexion', ru='Не удалось войти', hu='A bejelentkezés sikertelen', vi='Đăng nhập thất bại', ar='فشل تسجيل الدخول')
s('loggedInAs', en='Signed in as {name}', de='Angemeldet als {name}', fr='Connecté en tant que {name}', ru='Вы вошли как {name}', hu='Bejelentkezve: {name}', vi='Đã đăng nhập: {name}', ar='تم تسجيل الدخول باسم {name}')
s('logout', en='Sign out', de='Abmelden', fr='Se déconnecter', ru='Выйти', hu='Kijelentkezés', vi='Đăng xuất', ar='تسجيل الخروج')
s('logoutConfirm', en='Sign out? Your likes stay on this device.', de='Abmelden? Deine Likes bleiben auf diesem Gerät.', fr='Se déconnecter ? Vos titres aimés restent sur cet appareil.', ru='Выйти? Лайки останутся на этом устройстве.', hu='Kijelentkezel? A kedveléseid megmaradnak ezen az eszközön.', vi='Đăng xuất? Lượt thích vẫn được giữ trên thiết bị này.', ar='تسجيل الخروج؟ ستبقى إعجاباتك على هذا الجهاز.')
s('homeStream', en='Your stream', de='Dein Stream', fr='Votre flux', ru='Ваша лента', hu='Hírfolyamod', vi='Luồng của bạn', ar='بثّك')
s('scPlaylists', en='Your SoundCloud playlists', de='Deine SoundCloud-Playlists', fr='Vos playlists SoundCloud', ru='Ваши плейлисты SoundCloud', hu='SoundCloud-listáid', vi='Danh sách phát SoundCloud của bạn', ar='قوائم تشغيل SoundCloud الخاصة بك')
s('transferLikes', en='{count, plural, =1{Transfer 1 local like to your account?} other{Transfer {count} local likes to your account?}}', de='{count, plural, =1{1 lokalen Like in dein Konto übertragen?} other{{count} lokale Likes in dein Konto übertragen?}}', fr='{count, plural, one{Transférer {count} titre aimé local vers votre compte ?} other{Transférer {count} titres aimés locaux vers votre compte ?}}', ru='{count, plural, one{Перенести {count} локальный лайк в аккаунт?} few{Перенести {count} локальных лайка в аккаунт?} many{Перенести {count} локальных лайков в аккаунт?} other{Перенести {count} локальных лайка в аккаунт?}}', hu='{count, plural, other{Átviszel {count} helyi kedvelést a fiókodba?}}', vi='{count, plural, other{Chuyển {count} lượt thích cục bộ vào tài khoản?}}', ar='{count, plural, zero{لا توجد إعجابات محلية} one{نقل إعجاب محلي واحد إلى حسابك؟} two{نقل إعجابين محليين إلى حسابك؟} few{نقل {count} إعجابات محلية إلى حسابك؟} many{نقل {count} إعجابًا محليًا إلى حسابك؟} other{نقل {count} إعجاب محلي إلى حسابك؟}}')
s('transfer', en='Transfer', de='Übertragen', fr='Transférer', ru='Перенести', hu='Átvitel', vi='Chuyển', ar='نقل')
s('notNow', en='Not now', de='Nicht jetzt', fr='Pas maintenant', ru='Не сейчас', hu='Most nem', vi='Để sau', ar='ليس الآن')
s('loudTitle', en='Loudness mode', de='Laut/Leise-Modus', fr='Mode volume', ru='Режим громкости', hu='Hangerő-mód', vi='Chế độ âm lượng', ar='وضع الصوت')
s('loudDesc', en='Evens out loud and quiet tracks (ITU-R BS.1770) with a built-in limiter against clipping.', de='Gleicht laute und leise Titel an (ITU-R BS.1770), mit integriertem Limiter gegen Übersteuern.', fr='Égalise les titres forts et faibles (ITU-R BS.1770) avec un limiteur intégré contre la saturation.', ru='Выравнивает громкие и тихие треки (ITU-R BS.1770), встроенный лимитер защищает от перегрузки.', hu='Kiegyenlíti a hangos és halk számokat (ITU-R BS.1770), beépített limiterrel a túlvezérlés ellen.', vi='Cân bằng bài lớn và nhỏ (ITU-R BS.1770), có bộ giới hạn tích hợp chống méo tiếng.', ar='يوازن بين المقاطع العالية والمنخفضة (ITU-R BS.1770) مع محدِّد مدمج ضد التشويه.')
s('loudOff', en='Off', de='Aus', fr='Désactivé', ru='Выкл.', hu='Ki', vi='Tắt', ar='إيقاف')
s('loudQuiet', en='Quiet', de='Leise', fr='Faible', ru='Тихо', hu='Halk', vi='Nhỏ', ar='منخفض')
s('loudNormal', en='Normal', de='Normal', fr='Normal', ru='Норма', hu='Normál', vi='Bình thường', ar='عادي')
s('loudLoud', en='Loud', de='Laut', fr='Fort', ru='Громко', hu='Hangos', vi='Lớn', ar='مرتفع')
s('loudUnsupported', en='Not available on this platform yet', de='Auf dieser Plattform noch nicht verfügbar', fr='Pas encore disponible sur cette plateforme', ru='Пока недоступно на этой платформе', hu='Ezen a platformon még nem érhető el', vi='Chưa khả dụng trên nền tảng này', ar='غير متاح على هذه المنصة بعد')
s('signal', en='Signal', de='Signal', fr='Signal', ru='Сигнал', hu='Jel', vi='Tín hiệu', ar='الإشارة')
s('sigSource', en='Source', de='Quelle', fr='Source', ru='Источник', hu='Forrás', vi='Nguồn', ar='المصدر')
s('sigLoudness', en='Source loudness', de='Quell-Lautheit', fr='Sonie source', ru='Громкость источника', hu='Forrás hangossága', vi='Độ to nguồn', ar='جهارة المصدر')
s('sigMomentary', en='Momentary', de='Momentan', fr='Instantanée', ru='Мгновенная', hu='Pillanatnyi', vi='Tức thời', ar='لحظي')
s('sigGain', en='Gain', de='Verstärkung', fr='Gain', ru='Усиление', hu='Erősítés', vi='Độ lợi', ar='الكسب')
s('sigLimiter', en='Limiter', de='Limiter', fr='Limiteur', ru='Лимитер', hu='Limiter', vi='Bộ giới hạn', ar='المحدِّد')
s('sigOutput', en='Output', de='Ausgang', fr='Sortie', ru='Выход', hu='Kimenet', vi='Đầu ra', ar='المخرج')
s('sigAnalysis', en='Analysis', de='Analyse', fr='Analyse', ru='Анализ', hu='Elemzés', vi='Phân tích', ar='التحليل')
s('sigLive', en='Live FFT', de='Live-FFT', fr='FFT en direct', ru='FFT в реальном времени', hu='Élő FFT', vi='FFT trực tiếp', ar='FFT مباشر')
s('sigEnvelope', en='Waveform envelope', de='Wellenform-Hüllkurve', fr='Enveloppe de la forme d’onde', ru='Огибающая волны', hu='Hullámforma-burkoló', vi='Đường bao dạng sóng', ar='غلاف الموجة')
s('sigClip', en='Clipping', de='Übersteuert', fr='Saturation', ru='Перегрузка', hu='Túlvezérlés', vi='Quá tải', ar='تشويه')
s('sigClean', en='Clean', de='Sauber', fr='Propre', ru='Чисто', hu='Tiszta', vi='Sạch', ar='نظيف')
s('volume', en='Volume', de='Lautstärke', fr='Volume', ru='Громкость', hu='Hangerő', vi='Âm lượng', ar='مستوى الصوت')
s('mute', en='Mute', de='Stumm', fr='Muet', ru='Без звука', hu='Némítás', vi='Tắt tiếng', ar='كتم')
s('inspector', en='Inspector', de='Inspector', fr='Inspecteur', ru='Инспектор', hu='Inspector', vi='Bảng chi tiết', ar='لوحة التفاصيل')
s('expandPlayer', en='Focus view', de='Fokus-Ansicht', fr='Vue concentrée', ru='Режим фокуса', hu='Fókusz nézet', vi='Chế độ tập trung', ar='عرض التركيز')
s('expandRail', en='Expand sidebar', de='Leiste ausklappen', fr='Déplier la barre', ru='Развернуть панель', hu='Oldalsáv kinyitása', vi='Mở rộng thanh bên', ar='توسيع الشريط')
s('collapseRail', en='Collapse sidebar', de='Leiste einklappen', fr='Replier la barre', ru='Свернуть панель', hu='Oldalsáv becsukása', vi='Thu gọn thanh bên', ar='طي الشريط')
s('accentAmber', en='Electric Amber', de='Electric Amber', fr='Ambre électrique', ru='Электро-янтарь', hu='Elektromos borostyán', vi='Hổ phách điện', ar='كهرماني')
s('accentCyan', en='Cryo Cyan', de='Cryo Cyan', fr='Cyan cryo', ru='Крио-циан', hu='Krio cián', vi='Lam băng', ar='سماوي بارد')
s('accentCover', en='From artwork', de='Aus dem Cover', fr='Selon la pochette', ru='Из обложки', hu='A borítóból', vi='Theo ảnh bìa', ar='من الغلاف')
s('beatBg', en='Background in time with the beat', de='Hintergrund im Takt', fr='Arrière-plan en rythme', ru='Фон в такт музыке', hu='Háttér az ütemre', vi='Nền theo nhịp', ar='خلفية مع الإيقاع')
s('beatBgDesc', en='Colors pulse and change with every detected beat', de='Farben pulsieren und wechseln bei jedem erkannten Beat', fr='Les couleurs pulsent et changent à chaque temps détecté', ru='Цвета пульсируют и меняются на каждой доле', hu='A színek minden észlelt ütemre lüktetnek és váltanak', vi='Màu sắc nhấp nháy và đổi theo mỗi nhịp', ar='تنبض الألوان وتتغير مع كل نبضة مكتشفة')
s('beatLight', en='Light', de='Leicht', fr='Léger', ru='Слабо', hu='Enyhe', vi='Nhẹ', ar='خفيف')
s('beatMedium', en='Medium', de='Mittel', fr='Moyen', ru='Средне', hu='Közepes', vi='Vừa', ar='متوسط')
s('beatStrong', en='Strong', de='Stark', fr='Fort', ru='Сильно', hu='Erős', vi='Mạnh', ar='قوي')
s('appearance', en='Appearance', de='Darstellung', fr='Apparence', ru='Оформление', hu='Megjelenés', vi='Giao diện', ar='المظهر')
s('themeSystem', en='System', de='System', fr='Système', ru='Системная', hu='Rendszer', vi='Hệ thống', ar='النظام')
s('themeLight', en='Light', de='Hell', fr='Clair', ru='Светлая', hu='Világos', vi='Sáng', ar='فاتح')
s('themeDark', en='Dark', de='Dunkel', fr='Sombre', ru='Тёмная', hu='Sötét', vi='Tối', ar='داكن')
s('pureBlack', en='Pure black', de='Reines Schwarz', fr='Noir pur', ru='Чисто чёрный', hu='Tiszta fekete', vi='Đen tuyệt đối', ar='أسود خالص')
s('pureBlackDesc', en='Black background in dark mode (OLED)', de='Schwarzer Hintergrund im Dunkelmodus (OLED)', fr='Fond noir en mode sombre (OLED)', ru='Чёрный фон в тёмной теме (OLED)', hu='Fekete háttér sötét módban (OLED)', vi='Nền đen ở chế độ tối (OLED)', ar='خلفية سوداء في الوضع الداكن (OLED)')
s('dynamicColor', en='System colors', de='Systemfarben', fr='Couleurs du système', ru='Системные цвета', hu='Rendszerszínek', vi='Màu hệ thống', ar='ألوان النظام')
s('dynamicColorDesc', en="Use your system's accent color", de='Akzentfarbe des Systems verwenden', fr="Utiliser la couleur d'accentuation du système", ru='Использовать акцентный цвет системы', hu='A rendszer kiemelőszínének használata', vi='Dùng màu nhấn của hệ thống', ar='استخدام لون التمييز الخاص بالنظام')
s('artworkColors', en='Colors from artwork', de='Farben aus dem Cover', fr='Couleurs de la pochette', ru='Цвета обложки', hu='Színek a borítóból', vi='Màu theo ảnh bìa', ar='ألوان من الغلاف')
s('artworkColorsDesc', en='The player adapts its colors to the cover', de='Der Player passt seine Farben an das Cover an', fr='Le lecteur adapte ses couleurs à la pochette', ru='Плеер подстраивает цвета под обложку', hu='A lejátszó a borítóhoz igazítja a színeit', vi='Trình phát điều chỉnh màu theo ảnh bìa', ar='يكيّف المشغل ألوانه وفقًا للغلاف')
s('accentColor', en='Accent color', de='Akzentfarbe', fr="Couleur d'accentuation", ru='Акцентный цвет', hu='Kiemelőszín', vi='Màu nhấn', ar='لون التمييز')
s('language', en='Language', de='Sprache', fr='Langue', ru='Язык', hu='Nyelv', vi='Ngôn ngữ', ar='اللغة')
s('languageSystem', en='System default', de='Systemsprache', fr='Langue du système', ru='Язык системы', hu='Rendszer nyelve', vi='Mặc định hệ thống', ar='لغة النظام')
s('playback', en='Playback', de='Wiedergabe', fr='Lecture', ru='Воспроизведение', hu='Lejátszás', vi='Phát lại', ar='التشغيل')
s('quality', en='Stream quality', de='Streamqualität', fr='Qualité du streaming', ru='Качество потока', hu='Streamminőség', vi='Chất lượng phát', ar='جودة البث')
s('qualityHigh', en='High', de='Hoch', fr='Élevée', ru='Высокое', hu='Magas', vi='Cao', ar='عالية')
s('qualitySaver', en='Data saver', de='Datensparen', fr='Économie de données', ru='Экономия трафика', hu='Adattakarékos', vi='Tiết kiệm dữ liệu', ar='توفير البيانات')
s('autoplay', en='Autoplay', de='Autoplay', fr='Lecture automatique', ru='Автовоспроизведение', hu='Automatikus lejátszás', vi='Tự động phát', ar='التشغيل التلقائي')
s('autoplayDesc', en='Keep playing similar tracks when the queue ends', de='Nach der Warteschlange ähnliche Tracks weiterspielen', fr="Continuer avec des titres similaires à la fin de la file", ru='Продолжать похожими треками после очереди', hu='Hasonló számok lejátszása a sor végén', vi='Tiếp tục phát bài tương tự khi hết hàng đợi', ar='متابعة تشغيل مقاطع مشابهة عند انتهاء قائمة الانتظار')
s('network', en='Network', de='Netzwerk', fr='Réseau', ru='Сеть', hu='Hálózat', vi='Mạng', ar='الشبكة')
s('proxy', en='CORS proxy', de='CORS-Proxy', fr='Proxy CORS', ru='CORS-прокси', hu='CORS-proxy', vi='Proxy CORS', ar='وكيل CORS')
s('proxyDesc', en='Required in the browser, because SoundCloud only allows its own website.', de='Im Browser nötig, weil SoundCloud nur die eigene Website zulässt.', fr='Nécessaire dans le navigateur, car SoundCloud n\'autorise que son propre site.', ru='Нужен в браузере: SoundCloud разрешает запросы только со своего сайта.', hu='Böngészőben szükséges, mert a SoundCloud csak a saját oldalát engedi.', vi='Cần thiết trên trình duyệt vì SoundCloud chỉ cho phép trang web của họ.', ar='مطلوب في المتصفح لأن SoundCloud لا يسمح إلا بموقعه الخاص.')
s('about', en='About', de='Über', fr='À propos', ru='О приложении', hu='Névjegy', vi='Giới thiệu', ar='حول')
s('aboutText', en='Inspired by KittyTune by alan7383 and written from scratch in Flutter. Free software under GPL-3.0.', de='Inspiriert von KittyTune (alan7383), komplett neu in Flutter geschrieben. Freie Software unter GPL-3.0.', fr='Inspiré de KittyTune (alan7383), entièrement réécrit en Flutter. Logiciel libre sous GPL-3.0.', ru='Вдохновлено KittyTune (alan7383), написано с нуля на Flutter. Свободное ПО под GPL-3.0.', hu='A KittyTune (alan7383) ihlette, Flutterben az alapoktól megírva. Szabad szoftver, GPL-3.0.', vi='Lấy cảm hứng từ KittyTune (alan7383), viết mới hoàn toàn bằng Flutter. Phần mềm tự do theo GPL-3.0.', ar='مستوحى من KittyTune (alan7383) ومكتوب من الصفر بـ Flutter. برنامج حر بترخيص GPL-3.0.')
s('licenses', en='Open-source licenses', de='Open-Source-Lizenzen', fr='Licences open source', ru='Лицензии открытого ПО', hu='Nyílt forráskódú licencek', vi='Giấy phép mã nguồn mở', ar='تراخيص المصادر المفتوحة')

s('previewBadge', en='Preview (30s)', de='Vorschau (30 s)', fr='Extrait (30 s)', ru='Превью (30 с)', hu='Előnézet (30 mp)', vi='Bản nghe thử (30 giây)', ar='معاينة (30 ث)')
s('previewHint', en='SoundCloud only offers a 30-second preview of this track.', de='SoundCloud bietet von diesem Track nur eine 30-Sekunden-Vorschau an.', fr='SoundCloud ne propose qu’un extrait de 30 secondes de ce titre.', ru='SoundCloud предлагает только 30-секундное превью этого трека.', hu='A SoundCloud ebből a számból csak 30 másodperces előnézetet kínál.', vi='SoundCloud chỉ cung cấp bản nghe thử 30 giây của bài này.', ar='لا يقدّم SoundCloud سوى معاينة مدتها 30 ثانية لهذا المقطع.')
s('openInYtMusic', en='Open in YouTube Music', de='Auf YouTube Music öffnen', fr='Ouvrir dans YouTube Music', ru='Открыть в YouTube Music', hu='Megnyitás a YouTube Musicban', vi='Mở trong YouTube Music', ar='فتح في YouTube Music')
s('skipPreviews', en='Skip previews', de='Vorschauen überspringen', fr='Ignorer les extraits', ru='Пропускать превью', hu='Előnézetek kihagyása', vi='Bỏ qua bản nghe thử', ar='تخطي المعاينات')
s('skipPreviewsDesc', en='Skip 30-second previews when the queue moves on', de='30-Sekunden-Vorschauen beim Weiterschalten der Warteschlange auslassen', fr='Ignorer les extraits de 30 secondes lors du passage au titre suivant', ru='Пропускать 30-секундные превью при переходе по очереди', hu='A 30 másodperces előnézetek kihagyása a lejátszási sor léptetésekor', vi='Bỏ qua bản nghe thử 30 giây khi hàng đợi chuyển bài', ar='تخطي معاينات الثلاثين ثانية عند الانتقال في قائمة الانتظار')

s('fastStart', en='Fast start', de='Schnellstart', fr='Démarrage rapide', ru='Быстрый старт', hu='Gyorsindítás', vi='Khởi động nhanh', ar='بدء سريع')
s('fastStartDesc', en='Tapped tracks start as MP3 128 kbit/s – faster, slightly lower quality. Pre-buffered tracks keep the chosen quality.', de='Angetippte Tracks starten als MP3 128 kbit/s – schneller, etwas geringere Qualität. Vorgepufferte Tracks behalten die gewählte Qualität.', fr='Les titres touchés démarrent en MP3 128 kbit/s – plus rapide, qualité un peu moindre. Les titres préchargés gardent la qualité choisie.', ru='Выбранные треки запускаются как MP3 128 кбит/с – быстрее, чуть ниже качество. Предзагруженные треки сохраняют выбранное качество.', hu='A koppintott számok MP3 128 kbit/s-ként indulnak – gyorsabb, kicsit gyengébb minőség. Az előre pufferelt számok megtartják a választott minőséget.', vi='Bài được chạm sẽ phát dạng MP3 128 kbit/s – nhanh hơn, chất lượng hơi thấp hơn. Bài đã tải trước giữ chất lượng đã chọn.', ar='تبدأ المقاطع المختارة بصيغة MP3 بمعدل 128 كيلوبت/ث – أسرع مع جودة أقل قليلًا. تحتفظ المقاطع المحمّلة مسبقًا بالجودة المختارة.')

s('navDj', en='DJ', de='DJ', fr='DJ', ru='DJ', hu='DJ', vi='DJ', ar='دي جي')
s('djHeadline', en='Your DJ', de='Dein DJ', fr='Ton DJ', ru='Твой диджей', hu='A te DJ-d', vi='DJ của bạn', ar='الدي جي الخاص بك')
s('djIntro', en='Pick what you want to hear – Pounce mixes your likes and similar tracks, with transitions matched on key, tempo and drop.', de='Wähle, was du hören willst – Pounce mixt aus deinen Likes und Ähnlichem, mit Übergängen passend zu Tonart, Tempo und Drop.', fr='Choisis ce que tu veux écouter – Pounce mixe tes favoris et des titres similaires, avec des transitions calées sur la tonalité, le tempo et le drop.', ru='Выбери, что хочешь слушать, – Pounce сведёт твои лайки и похожие треки с переходами по тональности, темпу и дропу.', hu='Válaszd ki, mit hallgatnál – a Pounce a kedvenceidből és hasonló számokból mixel, hangnemhez, tempóhoz és drophoz illő átmenetekkel.', vi='Chọn thứ bạn muốn nghe – Pounce trộn các bài bạn thích và bài tương tự, chuyển bài khớp tông, nhịp và drop.', ar='اختر ما تريد سماعه – يمزج Pounce إعجاباتك ومقاطع مشابهة بانتقالات متوافقة مع المقام والإيقاع والدروب.')
s('djCategories', en='Categories', de='Kategorien', fr='Catégories', ru='Категории', hu='Kategóriák', vi='Thể loại', ar='الفئات')
s('djBlend', en='Blend', de='Mischung', fr='Mélange', ru='Смесь', hu='Keverék', vi='Tỉ lệ', ar='المزيج')
s('djFavorites', en='Favorites', de='Favoriten', fr='Favoris', ru='Избранное', hu='Kedvencek', vi='Yêu thích', ar='المفضلة')
s('djDiscover', en='Discover', de='Entdecken', fr='Découvrir', ru='Новое', hu='Felfedezés', vi='Khám phá', ar='اكتشاف')
s('djLookahead', en='Analyse ahead', de='Vorausanalyse', fr='Analyse anticipée', ru='Анализ заранее', hu='Előzetes elemzés', vi='Phân tích trước', ar='تحليل مسبق')
s('djLookaheadDesc', en='{count} songs ahead (~{mb} MB)', de='{count} Songs im Voraus (~{mb} MB)', fr='{count} titres à l’avance (~{mb} Mo)', ru='{count} треков заранее (~{mb} МБ)', hu='{count} szám előre (~{mb} MB)', vi='{count} bài trước (~{mb} MB)', ar='{count} مقطعًا مسبقًا (~{mb} م.ب)')
s('djStart', en='Start mix', de='Mix starten', fr='Lancer le mix', ru='Запустить микс', hu='Mix indítása', vi='Bắt đầu mix', ar='ابدأ المزج')
s('djBuilding', en='Building your mix…', de='Mix wird gebaut…', fr='Création du mix…', ru='Собираем микс…', hu='Mix készül…', vi='Đang tạo mix…', ar='جارٍ إنشاء المزج…')
s('djNothing', en='Nothing suitable found – try another category.', de='Nichts Passendes gefunden – probier eine andere Kategorie.', fr='Rien trouvé – essaie une autre catégorie.', ru='Ничего не найдено – попробуй другую категорию.', hu='Nincs találat – próbálj másik kategóriát.', vi='Không tìm thấy bài phù hợp – thử thể loại khác.', ar='لم يُعثر على شيء مناسب – جرّب فئة أخرى.')
s('djPickCategory', en='Pick at least one category', de='Wähle mindestens eine Kategorie', fr='Choisis au moins une catégorie', ru='Выбери хотя бы одну категорию', hu='Válassz legalább egy kategóriát', vi='Chọn ít nhất một thể loại', ar='اختر فئة واحدة على الأقل')
s('djAnalyzed', en='{done} of {total} songs analysed', de='{done} von {total} Songs analysiert', fr='{done} titres sur {total} analysés', ru='Проанализировано {done} из {total}', hu='{total} számból {done} elemezve', vi='Đã phân tích {done}/{total} bài', ar='تم تحليل {done} من {total}')
s('djMixStarted', en='Mix with {count} songs started', de='Mix mit {count} Songs gestartet', fr='Mix de {count} titres lancé', ru='Микс из {count} треков запущен', hu='{count} számos mix elindult', vi='Đã bắt đầu mix {count} bài', ar='بدأ مزج من {count} مقطعًا')

s('djStop', en='Stop DJ', de='DJ beenden', fr='Arrêter le DJ', ru='Выключить DJ', hu='DJ leállítása', vi='Dừng DJ', ar='إيقاف الدي جي')
s('djSkip', en='Skip (mixes over and learns)', de='Skip (blendet über und lernt)', fr='Passer (mixe et apprend)', ru='Пропустить (свести и запомнить)', hu='Kihagyás (átkever és tanul)', vi='Bỏ qua (chuyển mượt và học)', ar='تخطٍّ (مزج سلس وتعلّم)')

s('srcAll', en='All', de='Alle', fr='Tout', ru='Все', hu='Mind', vi='Tất cả', ar='الكل')
s('srcRadio', en='Web radio', de='Webradio', fr='Webradio', ru='Радио', hu='Webrádió', vi='Radio', ar='راديو الويب')
s('radioSection', en='Live radio · Stations', de='Live-Radio · Sender', fr='Radio en direct · Stations', ru='Прямой эфир · Станции', hu='Élő rádió · Adók', vi='Radio trực tiếp · Đài', ar='بث مباشر · محطات')
s('radioFavorites', en='Favourite stations', de='Lieblingssender', fr='Stations favorites', ru='Любимые станции', hu='Kedvenc adók', vi='Đài yêu thích', ar='المحطات المفضلة')
s('radioTop', en='Most listened', de='Meistgehört', fr='Les plus écoutées', ru='Самые популярные', hu='Legtöbbet hallgatott', vi='Nghe nhiều nhất', ar='الأكثر استماعًا')
s('radioAll', en='All stations', de='Alle Sender', fr='Toutes les stations', ru='Все станции', hu='Összes adó', vi='Tất cả đài', ar='كل المحطات')
s('radioSource', en='Web radio', de='Webradio', fr='Webradio', ru='Интернет-радио', hu='Webrádió', vi='Radio trực tuyến', ar='راديو الويب')
s('radioSourceDesc', en='Tens of thousands of stations from radio-browser.info. Off: no requests at all.', de='Zehntausende Sender von radio-browser.info. Aus: keine einzige Anfrage.', fr='Des dizaines de milliers de stations de radio-browser.info. Désactivé : aucune requête.', ru='Десятки тысяч станций с radio-browser.info. Выкл.: ни одного запроса.', hu='Több tízezer adó a radio-browser.info-ról. Kikapcsolva: egyetlen kérés sem.', vi='Hàng chục nghìn đài từ radio-browser.info. Tắt: không gửi yêu cầu nào.', ar='عشرات الآلاف من المحطات من radio-browser.info. عند الإيقاف: لا طلبات إطلاقًا.')
s('live', en='LIVE', de='LIVE', fr='DIRECT', ru='ЭФИР', hu='ÉLŐ', vi='TRỰC TIẾP', ar='مباشر')

s('updates', en='Updates', de='Updates', fr='Mises à jour', ru='Обновления', hu='Frissítések', vi='Cập nhật', ar='التحديثات')
s('updatesAuto', en='Check for updates automatically', de='Automatisch nach Updates suchen', fr='Rechercher les mises à jour automatiquement', ru='Проверять обновления автоматически', hu='Frissítések automatikus keresése', vi='Tự động kiểm tra cập nhật', ar='البحث عن التحديثات تلقائيًا')
s('updatesAutoDesc', en='At most once a day, one request to GitHub without any device ID. Never downloads by itself.', de='Höchstens einmal täglich, eine Anfrage an GitHub ohne Geräte-ID. Lädt nie selbst herunter.', fr='Au plus une fois par jour, une requête à GitHub sans identifiant d’appareil. Ne télécharge jamais seul.', ru='Не чаще раза в день, один запрос к GitHub без ID устройства. Сам ничего не скачивает.', hu='Legfeljebb naponta egyszer, egy kérés a GitHubnak eszközazonosító nélkül. Soha nem tölt le magától.', vi='Tối đa mỗi ngày một lần, một yêu cầu tới GitHub không kèm ID thiết bị. Không bao giờ tự tải xuống.', ar='مرة واحدة يوميًا كحد أقصى، طلب واحد إلى GitHub دون أي معرّف للجهاز. لا يُنزّل شيئًا من تلقاء نفسه.')
s('updatesCheck', en='Check now', de='Jetzt prüfen', fr='Vérifier', ru='Проверить', hu='Ellenőrzés', vi='Kiểm tra ngay', ar='تحقّق الآن')
s('updatesNone', en='Pounce is up to date', de='Pounce ist aktuell', fr='Pounce est à jour', ru='Pounce обновлён', hu='A Pounce naprakész', vi='Pounce đã là bản mới nhất', ar='Pounce محدّث')
s('updatesUnavailable', en='Updates are not available in this build', de='In diesem Build sind keine Updates verfügbar', fr='Pas de mises à jour dans cette version', ru='В этой сборке обновления недоступны', hu='Ebben a buildben nincs frissítés', vi='Bản dựng này không hỗ trợ cập nhật', ar='التحديثات غير متاحة في هذا الإصدار')
s('updateTitle', en='Update to {version}', de='Update auf {version}', fr='Mise à jour vers {version}', ru='Обновление до {version}', hu='Frissítés: {version}', vi='Cập nhật lên {version}', ar='تحديث إلى {version}')
s('updateDownload', en='Download & install ({mb} MB)', de='Herunterladen & installieren ({mb} MB)', fr='Télécharger et installer ({mb} Mo)', ru='Скачать и установить ({mb} МБ)', hu='Letöltés és telepítés ({mb} MB)', vi='Tải và cài đặt ({mb} MB)', ar='تنزيل وتثبيت ({mb} م.ب)')
s('updateViaPlay', en='Update via Google Play', de='Über Google Play aktualisieren', fr='Mettre à jour via Google Play', ru='Обновить через Google Play', hu='Frissítés a Google Playen', vi='Cập nhật qua Google Play', ar='التحديث عبر Google Play')
s('updateLater', en='Later', de='Später', fr='Plus tard', ru='Позже', hu='Később', vi='Để sau', ar='لاحقًا')
s('updateReleasePage', en='Release page', de='Release-Seite', fr='Page de la version', ru='Страница релиза', hu='Kiadás oldala', vi='Trang phát hành', ar='صفحة الإصدار')
s('updateChecksumFailed', en='Checksum mismatch – the download was discarded.', de='Prüfsumme stimmt nicht – der Download wurde verworfen.', fr='Somme de contrôle incorrecte – le téléchargement a été supprimé.', ru='Контрольная сумма не совпала – загрузка удалена.', hu='Hibás ellenőrzőösszeg – a letöltés törölve.', vi='Sai mã kiểm tra – bản tải đã bị huỷ.', ar='المجموع الاختباري غير مطابق – تم حذف التنزيل.')
s('updateNeedsPermission', en='Allow Pounce to install apps, then tap again.', de='Erlaube Pounce das Installieren von Apps und tippe dann erneut.', fr='Autorise Pounce à installer des applis, puis réessaie.', ru='Разреши Pounce устанавливать приложения и нажми снова.', hu='Engedélyezd a Pounce-nak az alkalmazások telepítését, majd koppints újra.', vi='Cho phép Pounce cài đặt ứng dụng rồi chạm lại.', ar='اسمح لـ Pounce بتثبيت التطبيقات ثم اضغط مجددًا.')
s('updateFailed', en='Update failed – please try again later.', de='Update fehlgeschlagen – bitte später erneut versuchen.', fr='Échec de la mise à jour – réessaie plus tard.', ru='Не удалось обновить – попробуй позже.', hu='A frissítés sikertelen – próbáld később.', vi='Cập nhật thất bại – thử lại sau.', ar='فشل التحديث – حاول لاحقًا.')

# Beta + setup wizard
s('beta', en='Beta', de='Beta', fr='Bêta', ru='Бета', hu='Béta', vi='Beta', ar='تجريبي')
s('betaNote', en='Pounce is in beta. Things may change or break – feedback on GitHub is very welcome.', de='Pounce ist in der Beta. Manches kann sich ändern oder haken – Feedback auf GitHub ist sehr willkommen.', fr='Pounce est en bêta. Certaines choses peuvent changer ou casser – vos retours sur GitHub sont les bienvenus.', ru='Pounce в бета-версии. Что-то может меняться или ломаться – отзывы на GitHub очень приветствуются.', hu='A Pounce béta. Valami változhat vagy elromolhat – a GitHubon szívesen fogadjuk a visszajelzést.', vi='Pounce đang ở giai đoạn beta. Một số thứ có thể thay đổi hoặc lỗi – rất hoan nghênh góp ý trên GitHub.', ar='Pounce في مرحلة تجريبية. قد تتغير بعض الأشياء أو تتعطل – ملاحظاتك على GitHub مرحب بها.')
s('setupWelcome', en='Welcome to Pounce', de='Willkommen bei Pounce', fr='Bienvenue dans Pounce', ru='Добро пожаловать в Pounce', hu='Üdv a Pounce-ban', vi='Chào mừng đến với Pounce', ar='مرحبًا بك في Pounce')
s('setupTagline', en='Fast music from SoundCloud and web radio – with a DJ that mixes for you.', de='Schnelle Musik von SoundCloud und Webradio – mit einem DJ, der für dich mixt.', fr='De la musique rapide depuis SoundCloud et la radio web – avec un DJ qui mixe pour vous.', ru='Быстрая музыка из SoundCloud и интернет-радио – с диджеем, который сводит для вас.', hu='Gyors zene SoundCloudról és webrádióból – egy DJ-vel, aki neked keverget.', vi='Nhạc nhanh từ SoundCloud và radio web – cùng một DJ trộn nhạc cho bạn.', ar='موسيقى سريعة من SoundCloud والراديو عبر الإنترنت – مع دي جي يمزج لك.')
s('setupStart', en="Let's go", de="Los geht's", fr="C'est parti", ru='Поехали', hu='Kezdjük', vi='Bắt đầu', ar='لنبدأ')
s('setupNext', en='Next', de='Weiter', fr='Suivant', ru='Далее', hu='Tovább', vi='Tiếp', ar='التالي')
s('setupBack', en='Back', de='Zurück', fr='Retour', ru='Назад', hu='Vissza', vi='Quay lại', ar='رجوع')
s('setupSkip', en='Skip setup', de='Einrichtung überspringen', fr='Passer la configuration', ru='Пропустить настройку', hu='Beállítás kihagyása', vi='Bỏ qua thiết lập', ar='تخطي الإعداد')
s('setupDone', en='Start listening', de='Musik starten', fr='Commencer à écouter', ru='Начать слушать', hu='Hallgatás indítása', vi='Bắt đầu nghe', ar='ابدأ الاستماع')
s('setupSourcesTitle', en='Where should music come from?', de='Woher soll die Musik kommen?', fr="D'où doit venir la musique ?", ru='Откуда брать музыку?', hu='Honnan jöjjön a zene?', vi='Nhạc lấy từ đâu?', ar='من أين تأتي الموسيقى؟')
s('setupSoundcloudDesc', en='Millions of tracks, mixes and remixes. Always on.', de='Millionen Tracks, Mixe und Remixe. Immer an.', fr='Des millions de titres, mixes et remixes. Toujours actif.', ru='Миллионы треков, миксов и ремиксов. Всегда включено.', hu='Milliónyi szám, mix és remix. Mindig be van kapcsolva.', vi='Hàng triệu bài hát, mix và remix. Luôn bật.', ar='ملايين المقاطع والمزجات والريمكسات. مفعّل دائمًا.')
s('setupRadioDesc', en='30,000+ stations via radio-browser.info. Off = no requests at all.', de='Über 30.000 Sender über radio-browser.info. Aus = keine einzige Anfrage.', fr='Plus de 30 000 stations via radio-browser.info. Désactivé = aucune requête.', ru='Более 30 000 станций через radio-browser.info. Выкл. = ни одного запроса.', hu='Több mint 30 000 állomás a radio-browser.info-n keresztül. Ki = egyetlen kérés sem.', vi='Hơn 30.000 đài qua radio-browser.info. Tắt = không gửi yêu cầu nào.', ar='أكثر من 30,000 محطة عبر radio-browser.info. إيقاف = لا طلبات إطلاقًا.')
s('setupAccountTitle', en='Bring your likes along?', de='Deine Likes mitnehmen?', fr='Importer vos titres aimés ?', ru='Перенести ваши лайки?', hu='Hozod a kedvenceidet?', vi='Mang theo lượt thích của bạn?', ar='هل تريد جلب إعجاباتك؟')
s('setupAccountDesc', en='Optional: sign in to SoundCloud to import likes and playlists. Pounce works fine without an account.', de='Optional: Melde dich bei SoundCloud an, um Likes und Playlists zu übernehmen. Pounce funktioniert auch ohne Konto.', fr='Facultatif : connectez-vous à SoundCloud pour importer titres aimés et playlists. Pounce fonctionne aussi sans compte.', ru='По желанию: войдите в SoundCloud, чтобы перенести лайки и плейлисты. Pounce работает и без аккаунта.', hu='Opcionális: jelentkezz be a SoundCloudba a kedvencek és listák átvételéhez. A Pounce fiók nélkül is működik.', vi='Tùy chọn: đăng nhập SoundCloud để nhập lượt thích và danh sách phát. Pounce vẫn hoạt động mà không cần tài khoản.', ar='اختياري: سجّل الدخول إلى SoundCloud لاستيراد الإعجابات وقوائم التشغيل. يعمل Pounce أيضًا بدون حساب.')
s('setupSignIn', en='Sign in to SoundCloud', de='Bei SoundCloud anmelden', fr='Se connecter à SoundCloud', ru='Войти в SoundCloud', hu='Bejelentkezés a SoundCloudba', vi='Đăng nhập SoundCloud', ar='تسجيل الدخول إلى SoundCloud')
s('setupDjTitle', en='What does your DJ play?', de='Was soll dein DJ spielen?', fr='Que doit jouer votre DJ ?', ru='Что будет играть ваш диджей?', hu='Mit játsszon a DJ-d?', vi='DJ của bạn sẽ phát gì?', ar='ماذا يشغّل الدي جي الخاص بك؟')
s('setupDjDesc', en='Pick a few styles. You can change them any time in the DJ tab.', de='Wähle ein paar Stile. Du kannst sie jederzeit im DJ-Tab ändern.', fr="Choisissez quelques styles. Modifiables à tout moment dans l'onglet DJ.", ru='Выберите несколько стилей. Их можно изменить во вкладке DJ.', hu='Válassz néhány stílust. A DJ fülön bármikor módosíthatod.', vi='Chọn vài phong cách. Bạn có thể đổi bất cứ lúc nào trong tab DJ.', ar='اختر بعض الأنماط. يمكنك تغييرها في أي وقت من تبويب DJ.')
s('setupPrivacyTitle', en='Your privacy', de='Deine Privatsphäre', fr='Votre vie privée', ru='Ваша конфиденциальность', hu='Az adataid', vi='Quyền riêng tư của bạn', ar='خصوصيتك')
s('setupPrivacyDesc', en='No tracking, no ads, no device IDs. Everything below is off unless you turn it on.', de='Kein Tracking, keine Werbung, keine Geräte-IDs. Alles hier ist aus, bis du es einschaltest.', fr="Pas de pistage, pas de pub, pas d'identifiant d'appareil. Tout est désactivé tant que vous ne l'activez pas.", ru='Без трекинга, рекламы и ID устройства. Всё ниже выключено, пока вы сами не включите.', hu='Nincs követés, reklám vagy eszközazonosító. Minden ki van kapcsolva, amíg be nem kapcsolod.', vi='Không theo dõi, không quảng cáo, không ID thiết bị. Mọi thứ dưới đây đều tắt cho đến khi bạn bật.', ar='لا تتبّع ولا إعلانات ولا معرّفات للجهاز. كل ما يلي معطّل حتى تفعّله.')
s('setupRecognition', en='Song recognition (Echolot)', de='Songerkennung (Echolot)', fr='Reconnaissance musicale (Echolot)', ru='Распознавание песен (Echolot)', hu='Dalfelismerés (Echolot)', vi='Nhận diện bài hát (Echolot)', ar='التعرّف على الأغاني (Echolot)')
s('setupRecognitionDesc', en='Coming in a later beta. Would send only anonymous audio fingerprints – never recordings – to the Echolot server.', de='Kommt in einer späteren Beta. Sendet nur anonyme Audio-Fingerabdrücke – nie Aufnahmen – an den Echolot-Server.', fr="Arrive dans une prochaine bêta. N'enverrait que des empreintes audio anonymes – jamais d'enregistrements – au serveur Echolot.", ru='Появится в следующей бете. Отправляет на сервер Echolot только анонимные аудиоотпечатки – никогда записи.', hu='Egy későbbi bétában érkezik. Csak névtelen hang-ujjlenyomatokat küld az Echolot szervernek – felvételt soha.', vi='Sẽ có trong bản beta sau. Chỉ gửi dấu vân tay âm thanh ẩn danh – không bao giờ gửi bản ghi âm – tới máy chủ Echolot.', ar='سيتوفر في إصدار تجريبي لاحق. يرسل فقط بصمات صوتية مجهولة – وليس تسجيلات أبدًا – إلى خادم Echolot.')
s('setupAgain', en='Run setup again', de='Einrichtung erneut starten', fr='Relancer la configuration', ru='Запустить настройку заново', hu='Beállítás újraindítása', vi='Chạy lại thiết lập', ar='إعادة تشغيل الإعداد')
s('version', en='Version {version}', de='Version {version}', fr='Version {version}', ru='Версия {version}', hu='Verzió: {version}', vi='Phiên bản {version}', ar='الإصدار {version}')

# Sync, engine, DJ deck
s('syncLast', en='Synced ({count} new events)', de='Synchronisiert ({count} neue Events)', fr='Synchronisé ({count} nouveaux événements)', ru='Синхронизировано (новых событий: {count})', hu='Szinkronizálva ({count} új esemény)', vi='Đã đồng bộ ({count} sự kiện mới)', ar='تمت المزامنة ({count} أحداث جديدة)')
s('syncTitle', en='Device sync', de='Gerätesynchronisation', fr='Synchronisation des appareils', ru='Синхронизация устройств', hu='Eszközszinkronizálás', vi='Đồng bộ thiết bị', ar='مزامنة الأجهزة')
s('syncBackground', en='Background sync', de='Hintergrund-Synchronisation', fr='Synchronisation en arrière-plan', ru='Фоновая синхронизация', hu='Háttérszinkronizálás', vi='Đồng bộ nền', ar='المزامنة في الخلفية')
s('syncServerActive', en='Server active (port {port}) · peer-to-peer on your local network', de='Server aktiv (Port {port}) · P2P-Sync im lokalen WLAN', fr='Serveur actif (port {port}) · pair-à-pair sur votre réseau local', ru='Сервер активен (порт {port}) · P2P в локальной сети', hu='Szerver aktív ({port}. port) · P2P a helyi hálózaton', vi='Máy chủ đang chạy (cổng {port}) · P2P trong mạng nội bộ', ar='الخادم نشط (المنفذ {port}) · نظير لنظير على شبكتك المحلية')
s('syncDisabled', en='Off', de='Deaktiviert', fr='Désactivé', ru='Выключено', hu='Kikapcsolva', vi='Tắt', ar='متوقف')
s('syncShowCode', en='Show pairing code', de='Kopplungscode anzeigen', fr="Afficher le code d'appairage", ru='Показать код сопряжения', hu='Párosítási kód megjelenítése', vi='Hiện mã ghép nối', ar='عرض رمز الاقتران')
s('syncShowCodeDesc', en='Code for your other devices', de='Code für andere Geräte zum Synchronisieren', fr='Code pour vos autres appareils', ru='Код для других устройств', hu='Kód a többi eszközödhöz', vi='Mã cho các thiết bị khác của bạn', ar='رمز لأجهزتك الأخرى')
s('syncCodeTitle', en='Pairing code', de='Kopplungscode', fr="Code d'appairage", ru='Код сопряжения', hu='Párosítási kód', vi='Mã ghép nối', ar='رمز الاقتران')
s('syncCodeHint', en='Enter this code on your other device:', de='Gib diesen Code auf deinem anderen Gerät ein:', fr='Saisissez ce code sur votre autre appareil :', ru='Введите этот код на другом устройстве:', hu='Írd be ezt a kódot a másik eszközödön:', vi='Nhập mã này trên thiết bị kia của bạn:', ar='أدخل هذا الرمز على جهازك الآخر:')
s('syncCodeCopied', en='Pairing code copied', de='Kopplungscode in Zwischenablage kopiert', fr="Code d'appairage copié", ru='Код сопряжения скопирован', hu='Párosítási kód másolva', vi='Đã sao chép mã ghép nối', ar='تم نسخ رمز الاقتران')
s('copy', en='Copy', de='Kopieren', fr='Copier', ru='Копировать', hu='Másolás', vi='Sao chép', ar='نسخ')
s('done', en='Done', de='Fertig', fr='Terminé', ru='Готово', hu='Kész', vi='Xong', ar='تم')
s('syncPair', en='Pair a device', de='Gerät koppeln', fr='Associer un appareil', ru='Подключить устройство', hu='Eszköz párosítása', vi='Ghép nối thiết bị', ar='إقران جهاز')
s('syncNoPeers', en='No other device connected', de='Kein anderes Gerät verbunden', fr='Aucun autre appareil connecté', ru='Нет подключённых устройств', hu='Nincs más eszköz csatlakoztatva', vi='Chưa kết nối thiết bị nào khác', ar='لا يوجد جهاز آخر متصل')
s('syncPeers', en='{count, plural, =1{1 device paired} other{{count} devices paired}}', de='{count, plural, =1{1 Gerät gekoppelt} other{{count} Geräte gekoppelt}}', fr='{count, plural, =1{1 appareil associé} other{{count} appareils associés}}', ru='{count, plural, one{{count} устройство} few{{count} устройства} many{{count} устройств} other{{count} устройства}}', hu='{count, plural, other{{count} eszköz párosítva}}', vi='{count, plural, other{Đã ghép {count} thiết bị}}', ar='{count, plural, =1{جهاز واحد مقترن} other{{count} أجهزة مقترنة}}')
s('syncPasteCode', en='Paste pairing code', de='Kopplungscode einfügen', fr="Collez le code d'appairage", ru='Вставьте код сопряжения', hu='Párosítási kód beillesztése', vi='Dán mã ghép nối', ar='الصق رمز الاقتران')
s('syncPairAction', en='Pair', de='Koppeln', fr='Associer', ru='Подключить', hu='Párosítás', vi='Ghép nối', ar='إقران')
s('syncPaired', en='Paired!', de='Erfolgreich gekoppelt!', fr='Appairé !', ru='Подключено!', hu='Párosítva!', vi='Đã ghép nối!', ar='تم الاقتران!')
s('syncPairFailed', en='Pairing failed', de='Kopplung fehlgeschlagen', fr="Échec de l'appairage", ru='Не удалось подключить', hu='A párosítás sikertelen', vi='Ghép nối thất bại', ar='فشل الاقتران')
s('syncNow', en='Sync now', de='Jetzt synchronisieren', fr='Synchroniser maintenant', ru='Синхронизировать сейчас', hu='Szinkronizálás most', vi='Đồng bộ ngay', ar='مزامنة الآن')
s('syncNever', en='Not synced yet', de='Noch nicht synchronisiert', fr='Pas encore synchronisé', ru='Ещё не синхронизировано', hu='Még nincs szinkronizálva', vi='Chưa đồng bộ', ar='لم تتم المزامنة بعد')
s('syncDone', en='Synced', de='Synchronisiert', fr='Synchronisé', ru='Синхронизировано', hu='Szinkronizálva', vi='Đã đồng bộ', ar='تمت المزامنة')
s('engineTitle', en='Audio engine & performance', de='Audio Engine & Performance', fr='Moteur audio et performances', ru='Аудиодвижок и производительность', hu='Hangmotor és teljesítmény', vi='Engine âm thanh & hiệu năng', ar='محرك الصوت والأداء')
s('engineRustDesc', en='{label} · beat grid, key (chroma), loudness and AI fingerprint from real audio', de='{label} · Beat-Raster, Tonart (Chroma), Lautheit, KI-Fingerabdruck aus echtem Audio', fr="{label} · grille rythmique, tonalité (chroma), loudness et empreinte IA à partir de l'audio réel", ru='{label} · сетка битов, тональность (хрома), громкость и ИИ-отпечаток по реальному звуку', hu='{label} · ütemrács, hangnem (kroma), hangosság és MI-ujjlenyomat valódi hangból', vi='{label} · lưới nhịp, tông (chroma), độ lớn và dấu vân tay AI từ âm thanh thật', ar='{label} · شبكة الإيقاع والمقام (كروما) وشدة الصوت وبصمة الذكاء الاصطناعي من الصوت الحقيقي')
s('engineUnavailable', en='Not available – estimate from the waveform only', de='Nicht verfügbar – nur Schätzung aus der Wellenform', fr="Indisponible – estimation à partir de la forme d'onde uniquement", ru='Недоступно – только оценка по форме волны', hu='Nem elérhető – csak becslés a hullámformából', vi='Không khả dụng – chỉ ước tính từ dạng sóng', ar='غير متاح – تقدير من شكل الموجة فقط')
s('djFlowActiveDesc', en='Automatic phrase & key matching', de='Autonome Phrasen- & Tonart-Abstimmung', fr='Calage automatique des phrases et tonalités', ru='Автоподбор фраз и тональности', hu='Automatikus frázis- és hangnemillesztés', vi='Tự động khớp câu nhạc & tông', ar='مطابقة تلقائية للجمل والمقام')
s('djTapToActivate', en='Tap to activate', de='Tippen zum Aktivieren', fr='Touchez pour activer', ru='Нажмите, чтобы включить', hu='Koppints az aktiváláshoz', vi='Chạm để bật', ar='اضغط للتفعيل')
s('djAnalyzing', en='Analysing audio…', de='Audio wird analysiert…', fr="Analyse de l'audio…", ru='Анализ аудио…', hu='Hang elemzése…', vi='Đang phân tích âm thanh…', ar='جارٍ تحليل الصوت…')
s('djNoKey', en='No key detected', de='Keine Tonart erkennbar', fr='Aucune tonalité détectée', ru='Тональность не определена', hu='Nem ismerhető fel hangnem', vi='Không nhận ra tông', ar='لم يُكتشف مقام')
s('djKeyUncertain', en='uncertain', de='unsicher', fr='incertain', ru='неуверенно', hu='bizonytalan', vi='không chắc', ar='غير مؤكد')
s('djBar', en='Bar {bar}/4', de='Takt {bar}/4', fr='Mesure {bar}/4', ru='Такт {bar}/4', hu='{bar}/4. ütem', vi='Ô nhịp {bar}/4', ar='المازورة {bar}/4')
s('djPhraseBeat', en='Phrase beat {beat}/16', de='Phrase Beat {beat}/16', fr='Temps de phrase {beat}/16', ru='Доля фразы {beat}/16', hu='Frázisütés {beat}/16', vi='Phách câu {beat}/16', ar='نبضة الجملة {beat}/16')
s('statGrid', en='Grid', de='Raster', fr='Grille', ru='Сетка', hu='Rács', vi='Lưới', ar='الشبكة')
s('statKey', en='Key', de='Tonart', fr='Tonalité', ru='Тональность', hu='Hangnem', vi='Tông', ar='المقام')
s('statLoudness', en='Loudness', de='Lautheit', fr='Loudness', ru='Громкость', hu='Hangosság', vi='Độ lớn', ar='شدة الصوت')
s('statEnergy', en='Energy', de='Energie', fr='Énergie', ru='Энергия', hu='Energia', vi='Năng lượng', ar='الطاقة')
s('statSource', en='Source', de='Quelle', fr='Source', ru='Источник', hu='Forrás', vi='Nguồn', ar='المصدر')
s('srcAudio', en='Audio', de='Audio', fr='Audio', ru='Аудио', hu='Hang', vi='Âm thanh', ar='الصوت')
s('srcWaveform', en='Waveform', de='Wellenform', fr="Forme d'onde", ru='Форма волны', hu='Hullámforma', vi='Dạng sóng', ar='شكل الموجة')
s('srcTitle', en='Title', de='Titel', fr='Titre', ru='Название', hu='Cím', vi='Tiêu đề', ar='العنوان')
s('djEnergiesLive', en='Audio energies (live)', de='Audio-Energien (live)', fr='Énergies audio (direct)', ru='Энергия аудио (live)', hu='Hangenergiák (élő)', vi='Năng lượng âm thanh (trực tiếp)', ar='طاقات الصوت (مباشر)')
s('djTransitionIn', en='Transition in {beats} beats', de='Übergang in {beats} Beats', fr='Transition dans {beats} temps', ru='Переход через {beats} долей', hu='Átmenet {beats} ütés múlva', vi='Chuyển sau {beats} phách', ar='انتقال بعد {beats} نبضات')
s('djEnergyMode', en='Harmonic energy mode', de='Harmonischer Energie-Modus', fr="Mode d'énergie harmonique", ru='Гармонический режим энергии', hu='Harmonikus energiamód', vi='Chế độ năng lượng hài hòa', ar='وضع الطاقة التوافقي')
s('djModeBuildUp', en='Build up', de='Aufbauen', fr='Monter', ru='Разогнать', hu='Felépítés', vi='Tăng dần', ar='تصاعد')
s('djModeHold', en='Hold', de='Halten', fr='Maintenir', ru='Держать', hu='Tartás', vi='Giữ', ar='ثبات')
s('djModeWindDown', en='Cool down', de='Abkühlen', fr='Redescendre', ru='Остыть', hu='Levezetés', vi='Hạ nhiệt', ar='تهدئة')
s('djHarmonic', en='Harmonic', de='Harmonisch', fr='Harmonique', ru='Гармонично', hu='Harmonikus', vi='Hài hòa', ar='توافقي')
s('djNextBest', en='Next track (best match)', de='Nächster Track (Bester Match)', fr='Titre suivant (meilleur accord)', ru='Следующий трек (лучшее совпадение)', hu='Következő szám (legjobb egyezés)', vi='Bài tiếp theo (khớp nhất)', ar='المقطع التالي (أفضل تطابق)')
s('djMatch', en='{pct}% match', de='{pct}% Match', fr="{pct} % d'accord", ru='Совпадение {pct}%', hu='{pct}% egyezés', vi='Khớp {pct}%', ar='تطابق {pct}%')
s('djMixNow', en='Mix now', de='Jetzt mixen', fr='Mixer maintenant', ru='Свести сейчас', hu='Keverés most', vi='Trộn ngay', ar='امزج الآن')
s('bandBass', en='BASS (kick & sub)', de='BASS (Kick & Sub)', fr='BASSES (kick & sub)', ru='БАС (бочка и саб)', hu='BASSZUS (lábdob és sub)', vi='BASS (kick & sub)', ar='الجهير (الركلة والسب)')
s('bandMid', en='MID (vocals & melody)', de='MID (Vocals & Melodie)', fr='MÉDIUMS (voix & mélodie)', ru='СЕРЕДИНА (вокал и мелодия)', hu='KÖZÉP (ének és dallam)', vi='TRUNG (giọng & giai điệu)', ar='الوسط (الغناء واللحن)')
s('bandHigh', en='HIGH (hi-hats & air)', de='HIGH (Hi-Hats & Air)', fr='AIGUS (charleston & air)', ru='ВЕРХ (хэты и воздух)', hu='MAGAS (cintányér és levegő)', vi='CAO (hi-hat & air)', ar='الحاد (الصنج والهواء)')
s('planDrop', en='Drop {time}', de='Drop {time}', fr='Drop {time}', ru='Дроп {time}', hu='Drop {time}', vi='Drop {time}', ar='الذروة {time}')
s('planNoDrop', en='no drop', de='kein Drop', fr='pas de drop', ru='без дропа', hu='nincs drop', vi='không có drop', ar='لا ذروة')
s('planSearching', en='looking for the drop…', de='Drop wird gesucht…', fr='recherche du drop…', ru='ищем дроп…', hu='drop keresése…', vi='đang tìm drop…', ar='جارٍ البحث عن الذروة…')
s('planText', en='Entry {entry} · {drop} · {fade} s fade', de='Einstieg {entry} · {drop} · {fade} s Blende', fr='Entrée {entry} · {drop} · fondu {fade} s', ru='Вход {entry} · {drop} · переход {fade} с', hu='Belépés {entry} · {drop} · {fade} mp áttűnés', vi='Vào {entry} · {drop} · chuyển {fade} giây', ar='الدخول {entry} · {drop} · تلاشٍ {fade} ث')

PH = {
  'homeBecauseYouPlayed': {'title': {'type': 'String'}},
  'deletePlaylistConfirm': {'name': {'type': 'String'}},
  'tracksCount': {'count': {'type': 'int'}},
  'followers': {'count': {'type': 'String'}},
  'addedToPlaylist': {'name': {'type': 'String'}},
  'alreadyInPlaylist': {'name': {'type': 'String'}},
  'lyricsSource': {'source': {'type': 'String'}},
  'sleepIn': {'minutes': {'type': 'int'}},
  'minutes': {'count': {'type': 'int'}},
  'loggedInAs': {'name': {'type': 'String'}},
  'transferLikes': {'count': {'type': 'int'}},
  'djLookaheadDesc': {'count': {'type': 'int'}, 'mb': {'type': 'int'}},
  'djAnalyzed': {'done': {'type': 'int'}, 'total': {'type': 'int'}},
  'djMixStarted': {'count': {'type': 'int'}},
  'updateTitle': {'version': {'type': 'String'}},
  'updateDownload': {'mb': {'type': 'String'}},
  'syncServerActive': {'port': {'type': 'int'}},
  'syncPeers': {'count': {'type': 'int'}},
  'syncLast': {'count': {'type': 'int'}},
  'engineRustDesc': {'label': {'type': 'String'}},
  'djBar': {'bar': {'type': 'int'}},
  'djPhraseBeat': {'beat': {'type': 'int'}},
  'djTransitionIn': {'beats': {'type': 'int'}},
  'djMatch': {'pct': {'type': 'String'}},
  'planDrop': {'time': {'type': 'String'}},
  'planText': {'entry': {'type': 'String'}, 'drop': {'type': 'String'}, 'fade': {'type': 'String'}},
  'version': {'version': {'type': 'String'}},
}
langs = ['en', 'de', 'fr', 'ru', 'hu', 'vi', 'ar']
os.makedirs('lib/l10n', exist_ok=True)
for lang in langs:
    out = {'@@locale': lang}
    for key, t in K.items():
        assert lang in t, (key, lang)
        out[key] = t[lang]
        if lang == 'en' and key in PH:
            out['@' + key] = {'placeholders': PH[key]}
    with open(f'lib/l10n/app_{lang}.arb', 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write('\n')
print(len(K), 'keys,', len(langs), 'languages')
